[global]
unity_version = "2022.3.35f1"
unity_hub_path = "E:/Unity Hub/Unity Hub.exe"
unity_editor_path = "E:/Unity Hub/Editor/2022.3.35f1/Editor/Unity.exe"
allowed_targets = ["windows", "linux", "mac"]
temp_project_path = "/tmp/unity"
clean_temp_project = false
link_method = "copy"

[bundles.vehiclemapframework]
description = "Bundle for Vehicle Map Framework"
output_directory = "E:/Program Files (x86)/Steam/steamapps/common/RimWorld/Mods/VehicleMapFramework/Common/AssetBundles"
asset_directory = "E:/Program Files (x86)/Steam/steamapps/common/RimWorld/Mods/VehicleMapFramework/Source/ArtSource"
bundle_name = "OELS.VehicleMapFramework"
filename = "textures"

[bundles.vehiclemapframeworkdev]
description = "Bundle for Vehicle Map Framework"
output_directory = "E:/Program Files (x86)/Steam/steamapps/common/RimWorld/Mods/VehicleMapFrameworkDev/Common/AssetBundles"
asset_directory = "E:/Program Files (x86)/Steam/steamapps/common/RimWorld/Mods/VehicleMapFramework/Source/ArtSource"
bundle_name = "OELS.VehicleMapFramework.dev"
filename = "textures"

[bundles.mapvehiclesoceanexpansion]
description = "Bundle for Map Vehicles -Ocean Expansion-"
output_directory = "../../Common/AssetBundles"
asset_directory = "./"
bundle_path = "OELS.MapVehicles.OceanExpansion"
bundle_name = "OELS.MapVehicles.OceanExpansion"
filename = "textures"
targetless = true
exclude_patterns = ["*.meta", "*.tmp"]
include_patterns = ["*.png", "*.wav", "*.ogg"]